version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Download osht.sh
          command: |
            cat /etc/*release
            curl -q -s https://raw.githubusercontent.com/coryb/osht/master/osht.sh --output osht.sh
            echo "export OSHT_LOCATION=$(pwd)/osht.sh" >> $BASH_ENV
      - run:
          command: |
            sudo apt-get -y install python3 make tar || :
      - run:
          command: |
            # python3 cannot be found unless remove this
            sudo rm /opt/circleci/.pyenv/shims/python3 || :
            make test_regen_all
      - run: PRIVILEGED_TESTS=1 make test
